Id: nvisionative.nvQuickSite
Version: 2.1.0
Name: nvQuickSite
Publisher: nvisionative
License: GPL3
LicenseUrl: https://github.com/nvisionative/nvQuickSite/blob/v2.1.0/nvQuickSite/LICENSE.md
AppMoniker: nvQuickSite
Tags: dnn, dotnetnuke, installer, website, cms
Description: nvQuickSite is a desktop installation app for DNN, the world's most popular ASP.NET-based CMS. This app allows you to easily install DNN onto any environment that meets the minimum system requirements for DNN to be installed.
Homepage: https://www.nvquicksite.com/
Installers:
  - Arch: Neutral
    Url: https://github.com/nvisionative/nvQuickSite/releases/download/v2.1.0/nvQuickSite_v2.1.0.0_Installer.msi
    Sha256: 5B738C2417A76A0D6D1660E6A2819E7337E615337EB6BA9447DE372727451460
    InstallerType: msi